version: '3'

services:
  nginx:
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    image: nginx:latest
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: ihome_nginx
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: ihome_app

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Zefirka_community
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"


